config/routes.rb
Rails.application.routes.draw do

  resources :posts do 
    resources :comments, only: [:index, :create, :edit, :update, :destroy]
  end

  root 'posts#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :post, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_post_content, only: [:index, :create, :edit, :update, :destroy]
  before_action :set_content, only: [:index, :create, :edit, :update, :destroy]

  def index
    @post = Post.find(params[:post_id])
    @comment = @post.comments
  end
    
    def create
      @post = Post.find(params[:post_id])
      @comment = @post.comments.build(comment_params)
      @post.save
      redirect_to post_comments_path(@post), notice: "El comentarios ha sido creado"
    end

      def edit
      @post = Post.find(params[:post_id])
      @comment = Comment.find(params[:id])
    end

    def destroy
      @post = Post.find(params[:post_id])
      @post.destroy      
      redirect_to post_posts_path(@post), notice: "El comentario ha sido eliminado"
    end  

    def update
      @post = Post.find(params[:post_id])
      @comment = Comment.find(params[:id])
      @comment.update(comment_params)
      redirect_to post_comments_path(@post), notice: "El comentario ha sido creado"
    end

    private 
    def comment_params
      params.require(:comment).permit(:content)
    end
    def post_params
      @post.destroy
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]


  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy(post_params)
    respond_to do |format|
        format.html { redirect_to @post, notice: 'Post was successfully destroyed.' }
        format.json { head :no_content }
     end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      
      @post = Post.all
      params.require(:post).permit(:title, :content)
      
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/index.html.erb
<h1 class="jumbotron"> Comments</h1>
<hr>
<table>
  <thead>
    <th>Post</th>
    <th>Content</th>
  </thead>
<tbody>
  <%= @comments.each do |comment| %>
    <tr>
      <td><%= comments.post.title%></td>
      <td><%= comment.content%></td>
      <td><%= link_to "Editar", edit_post_comment_path(@post,comment)%></td>
      <%= end %>
    </tr>
</tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogG10</title>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"> 

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_for(post) do |f| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <div class=""<%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :content %>
    <%= f.text_area :content %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>


<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<table class="table">
<thead>
  <h2>Vista previa</h2>
    <tr class="well well-sm">
      <th>Title</th>
      <th>Content</th>
      <th>Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.content %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Estás seguro?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<div class="jumbotron">
  <div class="container">
    <h1>Crea tu nuevo Post!</h1>
  </div>
</div>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
 
<p class="label label-success"><%= notice %></p>


<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @post.content %>
</p>
<br>
<hr>
<h2>Comentarios</h2>

<%= form_for [@post, Comment.new] do |f| %>
  <%= f.label :content, :comment %>
  <%= f.label :content, :comment %>
  <% end %>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>